# My Variables
@contentType = application/json
@baseUrl = http://localhost:9999/api
# @baseUrl = https://api.gwalletdev.com/api

###
# @name helloBotBank
GET {{baseUrl}}/bot-bank/hello
Content-Type:  {{contentType}}

###
# @name OperatorLogin
POST {{baseUrl}}/bot-bank/login
Content-Type:  {{contentType}}

{
    "ipAddress": "1.1.1.1",
    "type": "DEPOSIT"
}

###
# @name GetNameRetrieve
GET {{baseUrl}}/bot-bank/works/retrieve/next
Content-Type:  {{contentType}}

###
# @name ReportNameRetrieve
POST {{baseUrl}}/bot-bank/works/retrieve/report
Content-Type:  {{contentType}}

{
    "gmBankAccountId": "1595561944019",
    "toAccountNo": "1111122222",
    "toBankCode": "KBANK",
    "toAccountName": "Polly Diaz",
    "nameFromBank": "POLLY DIAZ"
}