export interface IVendor {
  code: string;
  name: string;
}

export const VENDORS: Record<string, IVendor> = {
  M8: { code: 'M8', name: 'M-Sports' },
  SSport: { code: 'SSport', name: 'S-Sports' },
  AB: { code: 'AB', name: 'AllBet' },
  AG: { code: 'AG', name: 'AG Deluxe Suite' },
  PT: { code: 'PT', name: 'SkyWind' },
  MX: { code: 'MX', name: 'Pragmatic' },
  ACE333: { code: 'ACE333', name: 'ACE333' },
  CF: { code: 'CF', name: 'CockFight' },
  CQ9: { code: 'CQ9', name: 'CQ9' },
  GG: { code: 'GG', name: 'Global Gaming' },
  WM: { code: 'WM', name: 'WM' },
  LS: { code: 'LS', name: 'Lucky Streak' },
  KN: { code: 'KN', name: 'Keno Lottery' },
  ML: { code: 'ML', name: 'ML' },
  DG: { code: 'DG', name: 'Dream Gamming' },
  GD: { code: 'DG', name: 'Gold Deluxe Casino' },
  SB: { code: 'SB', name: 'Sexy Baccarat' },
  VT: { code: 'VT', name: 'Virtual Tech' },
  CT855: { code: 'CT855', name: 'CT855' },
  SA: { code: 'SA', name: 'SA Gaming' },
  OG: { code: 'OG', name: 'OG Poker' },
  LEG: { code: 'LEG', name: 'LE Gaming' },
  SAE: { code: 'SAE', name: 'SA Gaming EGames' },
  FGG: { code: 'FGG', name: 'Fair Guaranted Gaming' },
  IA: { code: 'IA', name: 'IA E-Sports' },
  EVO: { code: 'EVO', name: 'Evolution Live Casino' },
  JOKER: { code: 'JOKER', name: 'JOKER' },
  DPT: { code: 'DPT', name: 'PlayTech Digital' },
  BG: { code: 'BG', name: 'BG Live Casino' },
  BGE: { code: 'BGE', name: 'BG E-Game' },
  C93: { code: 'C93', name: '93 Connect' },
  BS: { code: 'BS', name: 'BetSoft' },
  DT: { code: 'DT', name: 'DreamTech' },
  MaxBet: { code: 'MaxBet', name: 'Max Bet' },
  PPL: { code: 'PPL', name: 'PPL' },
  K8: { code: 'K8', name: 'KING855' },
  EZUGI: { code: 'EZUGI', name: 'EZUGI' },
  SBO: { code: 'SBO', name: 'SBO Sport' },
  SBOVS: { code: 'SBOVS', name: 'SBO Virtual Sport' },
  IG: { code: 'IG', name: 'IG E-games' },
  QQ: { code: 'QQ', name: 'QQLottery' },
};
