export enum ActionRequestType {
  DEPOSIT = 'DEPOSIT',
  WITHDRAW = 'WITHDRAW',
  TOPUP_CREDIT = 'TOPUP_CREDIT',
  REDUCE_CREDIT = 'REDUCE_CREDIT',
  OTHER = 'OTHER',
  CANCEL_WITHDRAW = 'CANCEL_WITHDRAW',
  DEPOSIT_TRUE_WALLET = 'DEPOSIT_TRUE_WALLET',
}
