export enum BalanceChangeUiType {
  DEPOSIT_AUTO = 'DEPOSIT_AUTO',
  DEPOSIT_MANUAL = 'DEPOSIT_MANUAL',
  DEPOSIT_MANUAL_BANK_MSG = 'DEPOSIT_MANUAL_BANK_MSG',
  WITHDRAW_AUTO = 'WITHDRAW_AUTO',
  WITHDRAW_MANUAL = 'WITHDRAW_MANUAL',
  TOPUP_CREDIT = 'TOPUP_CREDIT',
  REDUCE_CREDIT = 'REDUCE_CREDIT',
}
