export enum TxType {
  INIT = 'INIT',
  DEPOSIT = 'DEPOSIT',
  WITHDRAW = 'WITHDRAW',
  WITHDRAW_BANK = 'WITHDRAW_BANK',
  WITHDRAW_CANCEL = 'WITHDRAW_CANCEL',
  REDUCE_CREDIT = 'REDUCE_CREDIT',
  TOPUP_CREDIT = 'TOPUP_CREDIT',
  PROMOTION = 'PROMOTION',
  DEPOSIT_RETURN = 'DEPOSIT_RETURN',
  BANK_REPORT = 'BANK_REPORT',
  BANK_VERIFY = 'BANK_VERIFY',
  BANK_REFRESH = 'BANK_REFRESH',
}
