export enum WithdrawRequestStatus {
  NEW = 'NEW',
  CHECKING = 'CHECKING',
  WITHDRAWING = 'WITHDRAWING',
  REJECTED = 'REJECTED',
  FAILED = 'FAILED',
  SUCCESS = 'SUCCESS',
  MANUAL = 'MANUAL',
  CANCEL = 'CANCEL',
  ACTION_REQUEST = 'ACTION_REQUEST',
}
