export enum WorkStatus {
  TRANSFER_TO_IMI = 'TRANSFER_TO_IMI',
  TRANSFER_FROM_IMI = 'TRANSFER_FROM_IMI',
  TRANSFER_FROM_BANK = 'TRANSFER_FROM_BANK',
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
  CANCELED = 'CANCELED',
  IN_PROGRESS = 'IN_PROGRESS',
}
